### ISSUE TITLE
hh: add instructions for adding team external workers

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#45]
Hey,

After the ["Easier way to add team external workers" PR](https://github.com/helm/charts/pull/12056) got in, we should update the documentation around adding team external workers to hush-house.

```yaml
secrets:
  teamAuthorizedKeys:
    - team: foo
      key: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1OMDG...
```

Thanks!
