### ISSUE TITLE
metrics: reduce cadvisor cardinality

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#63]
Hey,

At the moment, there are a bunch of measurements arriving from `cadvisor` that simply don't matter for us:

- measurements from namespaces that we don't care about (e.g., `kube-system` stuff)
- metrics that are not valuable for us (I'm pretty sure we filter out a bunch)

To do so, we could introduce `metric_relabel_configs`:

```yaml
# drop any metrics from the `cadvisor` job that
# are not regarding the namespace that we want (`test`)
#
          metric_relabel_configs:
            - source_labels: [namespace]
              regex: 'test'
              action: keep
```

Thanks!
