### ISSUE TITLE
hh: pods getting evicted due to being low on ephemeral-storage

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#8]
Hey,

Despite now specifying a limit in the size of `emptyDir`, GKE has been evicting our workers:

```yaml
status:
  message: 'The node was low on resource: ephemeral-storage. Container hush-house-worker
    was using 73712Ki, which exceeds its request of 0. '
  phase: Failed
  reason: Evicted
  startTime: "2019-02-15T20:18:59Z"
```

It'd be good to see if there's anything configuration-wise that we did wrong 🤔
